name = "LinearResponseTDSCHA"
uuid = "ccc0b9a8-86cb-44d9-8e1a-f525e002c8b2"
authors = ["Lorenzo Monacelli <mesonepigreco@gmail.com>"]
version = "0.1.0"

[deps]
AtomicSymmetries = "7e24f7a5-8a44-4f91-9a93-7ee03df51e54"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
